Start using hipblas-common package
ROCmSoftwarePlatform/hipBLAS pull request #889
Opened 2024-07-08 22:09 UTC by bnemanich

resolves: hipBLASLt build dependency on hipBLAS by utilizing the hipBLAS-common package.

Summary of proposed changes:
- Removes datatypes that exist within hipBLAS-common package from hipBLAS
- Adds hipblas-common as a dependency to hipBLAS.

2024-07-09 20:53 UTC, daineAMD requested changes
- Should add a note in install.rst referencing the new dependency. Also potentially in functions.rst to reference the external types
- Need to get [Windows CI](https://mlsejenkinsvm.amd.com/blue/organizations/jenkins/ROCmMathLib%2FhipBLAS/detail/PR-889/2/pipeline/33) dependency available so windows CI isn't broken in hipBLAS. It looks to me like the packaging already exists in the hipblas-common repo, just needs CI running there, and the dependency added for hipBLAS CI
- Rerunning [pre-checkin CI](http://math-ci.amd.com/blue/organizations/jenkins/main%2Fprecheckin%2FhipBLAS/detail/PR-889/3/pipeline/442) to see if it passes

2024-08-09 18:02 UTC, daineAMD commented on rmake.py
> +    hipblas_common_path = f'"{raw_hipblas_common_path}"'
Yeah I guess would be good to add --hipblas_common_path cmd line argument. I can add it later though, doesn't have to hold up this PR.

2024-08-12 14:55 UTC, TorreZuk commented on library/src/CMakeLists.txt
> +  find_package( hipblas-common REQUIRED CONFIG PATHS "C:/hipSDK")
The C:/hipSDK should be changed to just ${ROCM_PATH} which should work on both WIN32 and linux

2024-08-13 15:45 UTC, TorreZuk commented on clients/CMakeLists.txt
> +endif()
Why would the clients find this package?   hipBLAS should capture include paths for its dependencies I think is the way this should go.

2024-08-13 15:46 UTC, TorreZuk commented on library/src/CMakeLists.txt
> +endif()
should remove hard coded C:/hipSDK but better to change both as per my earlier comment.

2024-08-15 15:57 UTC, daineAMD commented
Static CI looks like it's broken (for a long time). I'll see if I can test it out manually and approve afterwards.

2024-08-15 20:32 UTC, daineAMD approved these changes
Built static manually (without rocsolver) and seems to work ok. CI will be the real test but this should be fine and we can hotfix if needed.

2024-08-16 16:51 UTC, merged