[math-ci] changed CI dependencies (#908)
ROCmSoftwarePlatform/hipBLAS pull request #909
Opened 2024-08-27 17:03 UTC by amd-garydeng

Summary of proposed changes:
-dependency list change to support newer builds of rocBLAS

2024-09-03 18:00 UTC, daineAMD approved these changes

2024-09-04 17:32 UTC, TorreZuk commented
@amd-garydeng or @daineAMD should merge soon.

2024-09-04 21:56 UTC, TorreZuk requested changes
@amd-garydeng you messed up this PR with the develop merge.  You now want to remove the tip commit like git reset --hard HEAD^

2024-09-04 21:57 UTC, TorreZuk commented
> @amd-garydeng you messed up this PR with the develop merge. You now want to remove the tip commit like git reset --hard HEAD^

Or just start again with 6.3 and cherry pick if too messed up

2024-09-04 22:20 UTC, TorreZuk approved these changes

2024-09-04 22:20 UTC, amd-garydeng commented
@TorreZuk Just fixed it. Not sure why I merged develop into this.

2024-09-04 23:16 UTC, daineAMD approved these changes

2024-09-04 23:16 UTC, daineAMD commented on .jenkins/static.groovy
> +        prj.libraryDependencies = ['hipBLAS-common', 'hipBLASLt', 'rocBLAS']    }
weird formatting here

2024-09-05 14:54 UTC, TorreZuk commented
@amd-garydeng this looks good to merge with or without bracket formatting fix. It will unblock my PR CI

2024-09-05 17:20 UTC, merged